### ISSUE TITLE
[Q] Working?

### ISSUE THREAD

**Issue by Sineos** [zapta/ble_stepper_motor_analyzer#6]
I have received a bunch from JLCPCB.
I'd be grateful if you could take a look at https://drive.google.com/file/d/1WODmPNKCghbgU1xkgDg3Vb5cSd95qMt8/view
Is this what is to be expected, i.e. does it work like it should?

Basically just
```
G0 F9000 X245.0
G0 F9000 X1.0
```
repeated on a 0.9 stepper with 64 microsteps.

**Comment by zapta** [comment]
Looks very good.  The driver maintains a clean signal and high current at
high speed.

I cannot see well the current graph (third from the top). Ideally it should
be flat except for idle timeout where some drivers lower the current when
the motor doesn't move. Can you send me a closeup that shows the signal and
the Y axis?

**Comment by Sineos** [comment]
Playing around with the new toy currently :-)

![grafik](https://github.com/zapta/ble_stepper_motor_analyzer/assets/4459312/6ccc66bb-4f43-434c-a8aa-35f1b7c7c754)

What I'm wondering:

![grafik](https://github.com/zapta/ble_stepper_motor_analyzer/assets/4459312/51f41015-3fe7-4a47-9bd0-aa25c4346a88)

Why is this so asymmetrical, i.e. the Lissajous figure shifted to the right and top and the oscilloscope graph also shifted upwards?

**Comment by zapta** [comment]
Yes, I think that you need to calibrate the zeros of your sensor, it's a
one time thing, and it may also solve the fluctuations in the third graph
from the top.

1. With the power off, disconnect the stepper cables (to have zero current)
2. Power the analyzer the analyzer
3. Press on the button on the PCB for a few seconds until the LED will
blink 3 times, to indicate that the zero calibration values were stored
properly on the device.

Please let me know how it worked for you.

Also, since you have multiple boards, you may want to look into the 'nick
name' feature https://github.com/zapta/ble_stepper_motor_analyzer . You can
assign board names such as MOTOR_X or EXTRUDER and then use those names
instead of the numeric ids.

Zapta.

**Comment by zapta** [comment]
... the third graph (current) shows the radius of the circle you see in the
phase graph so if it's not centered by zero calibration, the radius is
different in different angles and thus the third graph shows fluctuation,
depending at what phase it happened to sample the X and Y currents. Very
interesting. Never seen it before because I always zero calibrate the
sensors first.

Zapta.

**Comment by Sineos** [comment]
![grafik](https://github.com/zapta/ble_stepper_motor_analyzer/assets/4459312/11681edd-d4f7-4ab4-988d-e846ec6fd844)
![grafik](https://github.com/zapta/ble_stepper_motor_analyzer/assets/4459312/1b6d5c8f-4ad6-4a19-b2c8-9c8df2c5418f)

*Sigh* A classic case of RTFM. Thanks for your support. Appreciated!

**Comment by zapta** [comment]
Awesome.  Thanks for updating me.

I learned something new.

**Comment by Sineos** [comment]
Thanks for the work and effort you put into providing this!
